# Originally created 2/10/2021 for the oci-tool project
#Define the stages in this pipeline
# Stages in each stage build in parallel except for before_script and after_script
stages:
   - test
   - build
   - deploy
# Eventually it'd be great if we could run clang-tidy and clang-format but the runner's host doesn't support it currently
test:
   stage: test
   script:
      - echo "Beginning test stage for $CI_PROJECT_NAME"
      - echo  "Running project build in $CI_PROJECT_DIR"
      - echo "Completed the test stage"
   rules:
      - if: "$CI_COMMIT_BRANCH == 'test'"

build:
   stage: build
   script:
      - echo "Beginning build stage for $CI_PROJECT_NAME"
      - mkdir -p /home/gitlabRunner/build_files/build
      - cd ~/build_files/build
      - cmake ~/build/$CI_PROJECT_DIR
      - make ~/build/$CI_PROJECT_DIR
      - make test ~/build/$CI_PROJECT_DIR
      - echo "Completed build stage"
   rules:
      - if: "$CI_COMMIT_BRANCH == 'test'"

deploy:
   stage: deploy
   script:
      - echo "Beginning the deploy stage for $CI_PROJECT_NAME"
      - echo "Deploy steps here - IF I HAD ANY"
      - echo "Completed the deploy stage, ending pipeline run"
   rules:
      - if: "$CI_COMMIT_BRANCH == 'test'"
