find_program(CLANG_C clang)
find_program(CLANG_CXX clang++)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

if (NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE Debug)
endif (NOT CMAKE_BUILD_TYPE)

if (CLANG_CXX)
  set(CMAKE_CXX_COMPILER ${CLANG_CXX})
  set(CMAKE_C_COMPILER ${CLANG_C})
endif (CLANG_CXX)

set(CMAKE_CXX_FLAGS "-Wall -Wnarrowing -Wextra -pedantic")
set(CMAKE_CXX_FLAGS_DEBUG "-O0 -g")
set(CMAKE_CXX_FLAGS_RELEASE "-O3")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "")
